gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl_update: true
  return_expiration: true
  cookie:
    enabled: true
    same_site: lax
    path: /
    domain: null
    http_only: true
    partitioned: false
    secure: true
    remove_token_from_body: true
