hwi_oauth:
    firewall_names: [main]
    
    resource_owners:        
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            scope: "user:email"
            options:
                csrf: true
                refresh_on_expire: true
            
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
            scope: "email profile"
