services:
  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    environment:
      - APP_ENV=dev

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb:11.7.2
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

  mailbox:
    image: mailhog/mailhog

  # mercure:
  #   image: dunglas/mercure
  #   restart: unless-stopped
  #   environment:
  #     SERVER_NAME: ':80'
  #     MERCURE_PUBLISHER_JWT_KEY: '%env(MERCURE_JWT_SECRET)%'
  #     MERCURE_SUBSCRIBER_JWT_KEY: '%env(MERCURE_JWT_SECRET)%'
  #     CORS_ALLOWED_ORIGINS: '*'
  #     PUBLISH_ALLOWED_ORIGINS: '*'
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - app-network

# volumes:
  db-data:
