services:
  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:root@database:3307/mealmates?serverVersion=8.0

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb:11.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: