# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.frontend_url: "%env(FRONTEND_URL)%"
  app.backend_url: "%env(BACKEND_URL)%"
  app.email_sender: "%env(EMAIL_SENDER)%"
  app.email_sender_name: "%env(EMAIL_SENDER_NAME)%"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\Security\OAuthUserProvider:
    arguments: ["@doctrine.orm.entity_manager"]

  hwi_oauth.user.provider.entity:
    alias: App\Security\OAuthUserProvider

  App\Controller\OAuthController:
    arguments:
      $params: "@parameter_bag"

  App\Controller\UserController:
    arguments:
      $params: "@parameter_bag"

  HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMap: "@hwi_oauth.resource_ownermap.main"

  App\Serializer\Normalizer\OfferNormalizer:
    tags:
      - { name: "serializer.normalizer", priority: 500 }
