<?php

namespace App\DataFixtures;

use App\Entity\Address;
use App\Entity\Allergen;
use App\Entity\FoodPreference;
use App\Entity\Image;
use App\Entity\Offer;
use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class OfferFixtures extends Fixture implements DependentFixtureInterface
{
    public const REFERENCE_IDENTIFIER = 'offer_';

    private const OFFERS = [
        [
            'identifier' => '1',
            'title' => 'Petits déjeuners',
            'description' => 'Produits de qualité à sauver du gaspillage',
            'quantity' => 7,
            'price' => 23,
            'dynamicPrice' => null,
            'allergens' => ['Fruits à coque'],
            'food_preferences' => ['Flexitarian'],
            'seller' => 'alicia',
            'address' => 'alicia_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '2',
            'title' => 'Légumineuses',
            'description' => 'Produits locaux à partager',
            'quantity' => 10,
            'price' => 18,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => [],
            'seller' => 'thomas',
            'address' => 'thomas_1',
            'buyer' => null,
            'isRecurring' => true,
            'soldAt' => null,
        ],
        [
            'identifier' => '3',
            'title' => 'Viande de boucherie',
            'description' => 'Surplus de mon restaurant',
            'quantity' => 5,
            'price' => 8,
            'dynamicPrice' => null,
            'allergens' => ['Arachides'],
            'food_preferences' => ['Flexitarian'],
            'seller' => 'alicia',
            'address' => 'alicia_2',
            'buyer' => null,
            'isRecurring' => true,
            'soldAt' => null,
        ],
        [
            'identifier' => '4',
            'title' => 'Herbes fraîches',
            'description' => 'Lot entier à récupérer',
            'quantity' => 3,
            'price' => 29,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => [],
            'seller' => 'admin',
            'address' => 'admin_4',
            'buyer' => 'thomas',
            'isRecurring' => false,
            'soldAt' => 'now',
        ],
        [
            'identifier' => '5',
            'title' => 'Pâtes fraîches',
            'description' => 'Produits du jour non vendus',
            'quantity' => 2,
            'price' => 18,
            'dynamicPrice' => 12.60,
            'allergens' => ['Fruits à coque', 'Lupin'],
            'food_preferences' => [],
            'seller' => 'david',
            'address' => 'david_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '6',
            'title' => 'Herbes fraîches',
            'description' => 'Excédent de production, parfait état',
            'quantity' => 3,
            'price' => 16,
            'dynamicPrice' => 11.20,
            'allergens' => ['Soja', 'Gluten'],
            'food_preferences' => [],
            'seller' => 'julie',
            'address' => 'julie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '7',
            'title' => 'Produits laitiers',
            'description' => 'Produits du marché de ce matin',
            'quantity' => 2,
            'price' => 12,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => [],
            'seller' => 'julie',
            'address' => 'julie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '8',
            'title' => 'Huile d\'olive extra vierge',
            'description' => 'Lot entier à récupérer',
            'quantity' => 8,
            'price' => 28,
            'dynamicPrice' => null,
            'allergens' => ['Lupin', 'Œufs'],
            'food_preferences' => [],
            'seller' => 'lucas',
            'address' => 'lucas_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '9',
            'title' => 'Fruits de saison',
            'description' => 'Produits du marché de ce matin',
            'quantity' => 8,
            'price' => 21,
            'dynamicPrice' => 14.70,
            'allergens' => ['Œufs'],
            'food_preferences' => [],
            'seller' => 'thomas',
            'address' => 'thomas_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '10',
            'title' => 'Plats préparés',
            'description' => 'Préparation en trop grande quantité',
            'quantity' => 4,
            'price' => 28,
            'dynamicPrice' => null,
            'allergens' => ['Anhydride sulfureux et sulfites', 'Œufs'],
            'food_preferences' => ['Vegan'],
            'seller' => 'lucas',
            'address' => 'lucas_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '11',
            'title' => 'Soupes fraîches',
            'description' => 'Surplus de mon repas de famille',
            'quantity' => 4,
            'price' => 23,
            'dynamicPrice' => null,
            'allergens' => ['Lait', 'Moutarde'],
            'food_preferences' => [],
            'seller' => 'alicia',
            'address' => 'alicia_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '12',
            'title' => 'Miel local',
            'description' => 'Produits de qualité premium à prix réduit',
            'quantity' => 1,
            'price' => 13,
            'dynamicPrice' => 9.10,
            'allergens' => ['Fruits à coque', 'Anhydride sulfureux et sulfites'],
            'food_preferences' => [],
            'seller' => 'sophie',
            'address' => 'sophie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '13',
            'title' => 'Soupes fraîches',
            'description' => 'Produits de qualité à sauver du gaspillage',
            'quantity' => 3,
            'price' => 1,
            'dynamicPrice' => 0.70,
            'allergens' => ['Lupin'],
            'food_preferences' => ['Vegetarian'],
            'seller' => 'sophie',
            'address' => 'sophie_2',
            'buyer' => 'nicolas',
            'isRecurring' => false,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '14',
            'title' => 'Snacks sains',
            'description' => 'Lot entier à récupérer',
            'quantity' => 2,
            'price' => 7,
            'dynamicPrice' => null,
            'allergens' => ['Gluten', 'Moutarde'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'maxime',
            'address' => 'maxime_2',
            'buyer' => 'alicia',
            'isRecurring' => true,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '15',
            'title' => 'Petits déjeuners',
            'description' => 'Aliments préparés avec soin à ne pas gaspiller',
            'quantity' => 1,
            'price' => 17,
            'dynamicPrice' => 11.90,
            'allergens' => [],
            'food_preferences' => ['Vegan'],
            'seller' => 'alicia',
            'address' => 'alicia_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '16',
            'title' => 'Pâtes fraîches',
            'description' => 'Trop pour ma consommation personnelle',
            'quantity' => 4,
            'price' => 9,
            'dynamicPrice' => null,
            'allergens' => ['Anhydride sulfureux et sulfites', 'Graines de sésame'],
            'food_preferences' => [],
            'seller' => 'alicia',
            'address' => 'alicia_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '17',
            'title' => 'Produits laitiers',
            'description' => 'Produits du jour non vendus',
            'quantity' => 9,
            'price' => 3,
            'dynamicPrice' => null,
            'allergens' => ['Arachides', 'Anhydride sulfureux et sulfites'],
            'food_preferences' => [],
            'seller' => 'nicolas',
            'address' => 'nicolas_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '18',
            'title' => 'Boissons végétales',
            'description' => 'Produits de qualité premium à prix réduit',
            'quantity' => 4,
            'price' => 8,
            'dynamicPrice' => 5.60,
            'allergens' => ['Anhydride sulfureux et sulfites', 'Céleri'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'lucas',
            'address' => 'lucas_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '19',
            'title' => 'Sauces maison',
            'description' => 'Achat en trop grande quantité',
            'quantity' => 3,
            'price' => 8,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'celine',
            'address' => 'celine_3',
            'buyer' => 'nicolas',
            'isRecurring' => false,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '20',
            'title' => 'Yaourts maison',
            'description' => 'Produits du marché de ce matin',
            'quantity' => 10,
            'price' => 20,
            'dynamicPrice' => null,
            'allergens' => ['Œufs'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'thomas',
            'address' => 'thomas_1',
            'buyer' => 'david',
            'isRecurring' => false,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '21',
            'title' => 'Œufs fermiers',
            'description' => 'Cultivé dans mon jardin, récolte abondante',
            'quantity' => 4,
            'price' => 30,
            'dynamicPrice' => 21.00,
            'allergens' => ['Arachides', 'Soja'],
            'food_preferences' => [],
            'seller' => 'admin',
            'address' => 'admin_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '22',
            'title' => 'Cafés de spécialité',
            'description' => 'Cultivé dans mon jardin, récolte abondante',
            'quantity' => 9,
            'price' => 4,
            'dynamicPrice' => null,
            'allergens' => ['Moutarde'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'sophie',
            'address' => 'sophie_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '23',
            'title' => 'Pâtes fraîches',
            'description' => 'Cultivé dans mon jardin, récolte abondante',
            'quantity' => 6,
            'price' => 3,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => ['Flexitarian'],
            'seller' => 'maxime',
            'address' => 'maxime_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '24',
            'title' => 'Confiture artisanale',
            'description' => 'Aliments préparés avec soin à ne pas gaspiller',
            'quantity' => 3,
            'price' => 14,
            'dynamicPrice' => null,
            'allergens' => ['Graines de sésame', 'Soja'],
            'food_preferences' => [],
            'seller' => 'maxime',
            'address' => 'maxime_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '25',
            'title' => 'Aliments fermentés',
            'description' => 'Préparation en trop grande quantité',
            'quantity' => 10,
            'price' => 12,
            'dynamicPrice' => 8.40,
            'allergens' => ['Graines de sésame', 'Arachides'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'julie',
            'address' => 'julie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '26',
            'title' => 'Viennoiseries',
            'description' => 'Surplus de mon restaurant',
            'quantity' => 9,
            'price' => 5,
            'dynamicPrice' => null,
            'allergens' => ['Soja'],
            'food_preferences' => [],
            'seller' => 'david',
            'address' => 'david_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '27',
            'title' => 'Snacks sains',
            'description' => 'Produits du jour non vendus',
            'quantity' => 5,
            'price' => 11,
            'dynamicPrice' => null,
            'allergens' => ['Gluten'],
            'food_preferences' => ['Vegetarian'],
            'seller' => 'celine',
            'address' => 'celine_3',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '28',
            'title' => 'Herbes fraîches',
            'description' => 'Achat en trop grande quantité',
            'quantity' => 10,
            'price' => 25,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => ['Vegetarian'],
            'seller' => 'julie',
            'address' => 'julie_2',
            'buyer' => 'david',
            'isRecurring' => false,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '29',
            'title' => 'Petits déjeuners',
            'description' => 'Produits du marché de ce matin',
            'quantity' => 3,
            'price' => 16,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => ['Vegan'],
            'seller' => 'thomas',
            'address' => 'thomas_3',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '30',
            'title' => 'Confiture artisanale',
            'description' => 'Lot entier à récupérer aujourd\'hui',
            'quantity' => 1,
            'price' => 4,
            'dynamicPrice' => null,
            'allergens' => ['Crustacés'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'julie',
            'address' => 'julie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '31',
            'title' => 'Yaourts maison',
            'description' => 'Produits locaux à partager',
            'quantity' => 8,
            'price' => 20,
            'dynamicPrice' => null,
            'allergens' => ['Soja'],
            'food_preferences' => [],
            'seller' => 'emilie',
            'address' => 'emilie_3',
            'buyer' => null,
            'isRecurring' => true,
            'soldAt' => null,
        ],
        [
            'identifier' => '32',
            'title' => 'Salades composées',
            'description' => 'Surplus de stock, prix réduit',
            'quantity' => 3,
            'price' => 15,
            'dynamicPrice' => null,
            'allergens' => ['Fruits à coque'],
            'food_preferences' => [],
            'seller' => 'sophie',
            'address' => 'sophie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '33',
            'title' => 'Panier de légumes bio',
            'description' => 'Cultivé dans mon jardin, récolte abondante',
            'quantity' => 2,
            'price' => 29,
            'dynamicPrice' => null,
            'allergens' => ['Mollusques', 'Crustacés'],
            'food_preferences' => ['Vegan'],
            'seller' => 'alicia',
            'address' => 'alicia_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '34',
            'title' => 'Noix et fruits secs',
            'description' => 'Erreur de commande, produits impeccables',
            'quantity' => 1,
            'price' => 15,
            'dynamicPrice' => 10.50,
            'allergens' => ['Soja'],
            'food_preferences' => ['Vegan'],
            'seller' => 'julie',
            'address' => 'julie_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '35',
            'title' => 'Soupes fraîches',
            'description' => 'Erreur de commande, produits impeccables',
            'quantity' => 6,
            'price' => 26,
            'dynamicPrice' => null,
            'allergens' => ['Poisson'],
            'food_preferences' => [],
            'seller' => 'maxime',
            'address' => 'maxime_1',
            'buyer' => 'admin',
            'isRecurring' => false,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '36',
            'title' => 'Légumineuses',
            'description' => 'Produits frais à consommer rapidement',
            'quantity' => 9,
            'price' => 9,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => [],
            'seller' => 'admin',
            'address' => 'admin_4',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '37',
            'title' => 'Miel local',
            'description' => 'Lot entier à récupérer',
            'quantity' => 2,
            'price' => 12,
            'dynamicPrice' => null,
            'allergens' => ['Gluten'],
            'food_preferences' => ['Vegan'],
            'seller' => 'sophie',
            'address' => 'sophie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '38',
            'title' => 'Noix et fruits secs',
            'description' => 'Produits de qualité premium à prix réduit',
            'quantity' => 7,
            'price' => 28,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => ['Vegan'],
            'seller' => 'lucas',
            'address' => 'lucas_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '39',
            'title' => 'Noix et fruits secs',
            'description' => 'Surplus de mon restaurant',
            'quantity' => 6,
            'price' => 24,
            'dynamicPrice' => null,
            'allergens' => ['Mollusques', 'Lait'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'thomas',
            'address' => 'thomas_3',
            'buyer' => 'emilie',
            'isRecurring' => false,
             'soldAt' => 'now',
        ],
        [
            'identifier' => '40',
            'title' => 'Miel local',
            'description' => 'Surplus de stock, prix réduit',
            'quantity' => 1,
            'price' => 7,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => [],
            'seller' => 'maxime',
            'address' => 'maxime_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '41',
            'title' => 'Viennoiseries',
            'description' => 'Surplus de stock, prix réduit',
            'quantity' => 5,
            'price' => 27,
            'dynamicPrice' => null,
            'allergens' => ['Poisson', 'Fruits à coque'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'alicia',
            'address' => 'alicia_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '42',
            'title' => 'Thés et tisanes',
            'description' => 'Erreur de commande, produits impeccables',
            'quantity' => 9,
            'price' => 5,
            'dynamicPrice' => null,
            'allergens' => ['Graines de sésame', 'Œufs'],
            'food_preferences' => ['Vegetarian'],
            'seller' => 'alicia',
            'address' => 'alicia_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '43',
            'title' => 'Légumineuses',
            'description' => 'Lot entier à récupérer aujourd\'hui',
            'quantity' => 4,
            'price' => 12,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => ['Flexitarian'],
            'seller' => 'sophie',
            'address' => 'sophie_1',
            'buyer' => null,
            'isRecurring' => true,
            'soldAt' => null,
        ],
        [
            'identifier' => '44',
            'title' => 'Aliments fermentés',
            'description' => 'Produits locaux à partager',
            'quantity' => 3,
            'price' => 8,
            'dynamicPrice' => 5.60,
            'allergens' => ['Gluten'],
            'food_preferences' => ['Flexitarian'],
            'seller' => 'alicia',
            'address' => 'alicia_2',
            'buyer' => null,
            'isRecurring' => true,
            'soldAt' => null,
        ],
        [
            'identifier' => '45',
            'title' => 'Produits laitiers',
            'description' => 'Excédent de production, parfait état',
            'quantity' => 3,
            'price' => 16,
            'dynamicPrice' => 11.20,
            'allergens' => ['Gluten', 'Moutarde'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'nicolas',
            'address' => 'nicolas_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '46',
            'title' => 'Épices rares',
            'description' => 'Lot entier à récupérer aujourd\'hui',
            'quantity' => 4,
            'price' => 7,
            'dynamicPrice' => null,
            'allergens' => [],
            'food_preferences' => [],
            'seller' => 'julie',
            'address' => 'julie_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '47',
            'title' => 'Herbes fraîches',
            'description' => 'Achat en trop grande quantité',
            'quantity' => 2,
            'price' => 28,
            'dynamicPrice' => 19.60,
            'allergens' => ['Graines de sésame'],
            'food_preferences' => ['Pescatarian'],
            'seller' => 'lucas',
            'address' => 'lucas_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '48',
            'title' => 'Repas végétariens',
            'description' => 'Lot entier à récupérer aujourd\'hui',
            'quantity' => 10,
            'price' => 9,
            'dynamicPrice' => null,
            'allergens' => ['Fruits à coque'],
            'food_preferences' => [],
            'seller' => 'david',
            'address' => 'david_1',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '49',
            'title' => 'Viennoiseries',
            'description' => 'Produits frais à consommer rapidement',
            'quantity' => 8,
            'price' => 22,
            'dynamicPrice' => null,
            'allergens' => ['Graines de sésame', 'Mollusques'],
            'food_preferences' => [],
            'seller' => 'maxime',
            'address' => 'maxime_2',
            'buyer' => null,
            'isRecurring' => false,
            'soldAt' => null,
        ],
        [
            'identifier' => '50',
            'title' => 'Huile d\'olive extra vierge',
            'description' => 'Produits de mon commerce à sauver',
            'quantity' => 8,
            'price' => 9,
            'dynamicPrice' => 6.30,
            'allergens' => ['Crustacés'],
            'food_preferences' => ['Vegetarian'],
            'seller' => 'maxime',
            'address' => 'maxime_1',
            'buyer' => 'thomas',
            'isRecurring' => false,
             'soldAt' => 'now',
        ]
    ];

    public function load(ObjectManager $manager): void
    {
        $dates = ['+1 day', '+2 days', '+1 week'];

        foreach (self::OFFERS as $data) {
            $offer = new Offer();
            $offer->setName($data['title']);
            $offer->setDescription($data['description']);
            $offer->setPrice($data['price']);
            $offer->setQuantity($data['quantity']);
            $offer->setDynamicPrice($data['dynamicPrice']);
            $offer->setIsRecurring($data['isRecurring']);

            if (null !== $data['soldAt']) {
                $offer->setSoldAt(new \DateTime($data['soldAt'] === 'now' ? 'now' : $data['soldAt']));
            }

            $offer->setSeller($this->getReference(UserFixtures::REFERENCE_IDENTIFIER . $data['seller'], User::class));
            if ($data['buyer']) {
                $offer->setBuyer($this->getReference(UserFixtures::REFERENCE_IDENTIFIER . $data['buyer'], User::class));
            }
            foreach ($data['allergens'] as $allergen) {
                $offer->addAllergen($this->getReference(AllergenFixtures::REFERENCE_IDENTIFIER . $allergen, Allergen::class));
            }
            foreach ($data['food_preferences'] as $foodPreference) {
                $offer->addFoodPreference($this->getReference(FoodPreferenceFixtures::REFERENCE_IDENTIFIER . $foodPreference, FoodPreference::class));
            }

            $offer->setAddress($this->getReference(AddressFixtures::REFERENCE_IDENTIFIER . $data['address'], Address::class));
            $offer->setExpiryDate(new \DateTimeImmutable($dates[array_rand($dates)]));

            $manager->persist($offer);
            $this->addReference(self::REFERENCE_IDENTIFIER . $data['identifier'], $offer);
        }

        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            UserFixtures::class,
            AddressFixtures::class,
            AllergenFixtures::class,
            FoodPreferenceFixtures::class,
        ];
    }
}
